// Copyright 2025
// Licensed under the Elastic License v2.0

//! Active-chunk registry for the read-only DBLog incremental snapshot
//! reconciliation (T4 / B4).
//!
//! While a MySQL snapshot worker reads a PK-bounded chunk, the binlog
//! stream consumer keeps running. Any binlog event that mutates a row in
//! the chunk's PK range and whose GTID falls inside the chunk's window
//! `(LOW, HIGH]` must override the row read by the snapshot — otherwise
//! the snapshot would write stale data to the sink.
//!
//! This module is the synchronisation point between the two: snapshot
//! workers register their chunks here, the consumer marks evictions and
//! signals the worker once its window has closed.
//!
//! The data structure is a small `HashMap<ChunkId, ChunkState>` guarded
//! by a single `RwLock`. Active chunk count = number of in-flight
//! snapshot workers (default 1, capped at the configured parallelism),
//! so contention is negligible. Each chunk owns its own `Notify` so the
//! worker only wakes when its specific window has closed.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;

use tokio::sync::{Notify, RwLock};

use crate::core::Value;
use crate::source::mysql::gtid::GtidSet;

/// Stable identifier for a snapshot chunk during its lifetime in the
/// registry. Generated by `ActiveChunks::register`.
pub type ChunkId = u64;

/// Hash-friendly representation of a primary-key value.
///
/// `Value` includes `Float64`, which doesn't implement `Eq`/`Hash`, so we
/// can't keep evicted PKs as `HashSet<Value>` directly. The snapshot
/// chunker only chunks on integer / string / uuid PKs in practice, all
/// of which round-trip losslessly through this format.
pub type PkKey = String;

/// Stable string encoding of a `Value` for use in `HashSet<PkKey>`.
/// Different variants get different prefixes so e.g. `Int64(1)` and
/// `String("1")` never collide.
pub fn pk_key(value: &Value) -> PkKey {
    match value {
        Value::Int64(i) => format!("i:{}", i),
        Value::String(s) => format!("s:{}", s),
        Value::Uuid(u) => format!("u:{}", u),
        Value::Decimal(d) => format!("d:{}", d),
        Value::Bytes(b) => format!("b:{}", hex_encode(b)),
        Value::Bool(b) => format!("B:{}", b),
        Value::Timestamp(t) => format!("t:{}", t),
        // Float / Json / Null / Unchanged are not valid PK types in
        // dbmazz's chunker, but we still want a deterministic key so
        // a misuse doesn't silently collapse rows together.
        other => format!("?:{:?}", other),
    }
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

/// Mutable per-chunk state shared between snapshot worker and binlog
/// consumer. All fields are mutated through `ActiveChunks` to keep the
/// locking discipline in one place.
#[derive(Debug)]
pub struct ChunkState {
    /// Fully-qualified table the chunk belongs to (`schema`, `table`).
    pub table: (String, String),
    /// Primary key column name (single-column PKs only — matches the
    /// rest of the snapshot module's assumptions).
    pub pk_column: String,
    /// Inclusive PK range `[start, end]` covered by this chunk.
    pub pk_range: (Value, Value),
    /// `@@global.gtid_executed` captured immediately before the chunk's
    /// `SELECT`. The lower bound of the reconciliation window.
    pub low_set: GtidSet,
    /// `@@global.gtid_executed` captured immediately after the chunk's
    /// `SELECT`. `None` while the `SELECT` is still in flight.
    pub high_set: Option<GtidSet>,
    /// PKs whose row in this chunk has been overridden by a later binlog
    /// event in the window — the worker must drop these from the buffer
    /// before emitting to the sink.
    pub evicted_pks: HashSet<PkKey>,
    /// Set to `true` once the consumer's running `gtid_executed` is a
    /// superset of `high_set`, meaning every event that could possibly
    /// have fallen in the window has been seen.
    pub drained: bool,
    /// Wakes the snapshot worker waiting in `await_drain`.
    pub notify: Arc<Notify>,
}

/// Process-wide registry of active snapshot chunks.
///
/// Cheaply cloneable — the inner state is shared via `Arc`. One instance
/// is constructed per `CdcEngine::run` and threaded into every snapshot
/// worker and into the `MysqlReplicationLoop`.
#[derive(Clone, Default, Debug)]
pub struct ActiveChunks {
    inner: Arc<Inner>,
}

#[derive(Default, Debug)]
struct Inner {
    chunks: RwLock<HashMap<ChunkId, ChunkState>>,
    next_id: std::sync::atomic::AtomicU64,
}

/// RAII handle returned by `register`. Callers may either pass it to
/// `deregister` explicitly or rely on it being dropped — both paths
/// remove the chunk from the registry.
#[must_use = "drop or pass to ActiveChunks::deregister to release the chunk"]
pub struct ChunkHandle {
    id: ChunkId,
    chunks: ActiveChunks,
}

impl ChunkHandle {
    pub fn id(&self) -> ChunkId {
        self.id
    }
}

impl Drop for ChunkHandle {
    fn drop(&mut self) {
        let chunks = self.chunks.clone();
        let id = self.id;
        // Spawn a task to release the lock since Drop can't be async.
        // Worst case the chunk hangs around a bit longer; correctness is
        // not affected because in-flight events for a deregistered table
        // simply find no matching chunk.
        tokio::spawn(async move {
            chunks.deregister(id).await;
        });
    }
}

impl ActiveChunks {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a chunk and return a handle. The notify field is owned
    /// by the chunk and shared with the caller so they can wait on it.
    pub async fn register(
        &self,
        table: (String, String),
        pk_column: String,
        pk_range: (Value, Value),
        low_set: GtidSet,
    ) -> (ChunkHandle, Arc<Notify>) {
        let id = self
            .inner
            .next_id
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let notify = Arc::new(Notify::new());
        let state = ChunkState {
            table,
            pk_column,
            pk_range,
            low_set,
            high_set: None,
            evicted_pks: HashSet::new(),
            drained: false,
            notify: notify.clone(),
        };
        self.inner.chunks.write().await.insert(id, state);
        let handle = ChunkHandle {
            id,
            chunks: self.clone(),
        };
        (handle, notify)
    }

    /// Set the chunk's `high_set` once the SELECT has finished. After
    /// this point, drain detection is meaningful.
    pub async fn set_high_watermark(&self, id: ChunkId, high_set: GtidSet) {
        if let Some(state) = self.inner.chunks.write().await.get_mut(&id) {
            state.high_set = Some(high_set);
        }
    }

    /// Mark a PK as overridden by a binlog event. Idempotent — repeated
    /// calls for the same `(chunk, pk)` are no-ops.
    ///
    /// The caller is responsible for ensuring the event's GTID falls in
    /// the chunk's window; this method just records the eviction.
    pub async fn record_eviction(&self, id: ChunkId, pk: &Value) {
        if let Some(state) = self.inner.chunks.write().await.get_mut(&id) {
            state.evicted_pks.insert(pk_key(pk));
        }
    }

    /// Snapshot the current set of evicted PK keys for a chunk. Used by
    /// the snapshot worker right before emitting the reconciled buffer.
    pub async fn evicted_pks(&self, id: ChunkId) -> HashSet<PkKey> {
        self.inner
            .chunks
            .read()
            .await
            .get(&id)
            .map(|s| s.evicted_pks.clone())
            .unwrap_or_default()
    }

    /// Walk every active chunk; for each whose `high_set` has been set
    /// and whose window is now covered by `consumer_gtid_set`, mark it
    /// drained and notify its waiter.
    ///
    /// Called by the binlog consumer after each event so workers wake
    /// up promptly. Cheap: chunk count is the snapshot parallelism.
    pub async fn try_drain(&self, consumer_gtid_set: &GtidSet) {
        let mut chunks = self.inner.chunks.write().await;
        for state in chunks.values_mut() {
            if state.drained {
                continue;
            }
            if let Some(high) = &state.high_set {
                if consumer_gtid_set.is_superset_of(high) {
                    state.drained = true;
                    state.notify.notify_waiters();
                }
            }
        }
    }

    /// Wait until the chunk is marked drained.
    ///
    /// Returns immediately if it already is. The caller passes the
    /// `Notify` returned by `register`; we re-check the flag after
    /// each wake to handle spurious wakeups.
    pub async fn await_drain(&self, id: ChunkId, notify: Arc<Notify>) {
        loop {
            let already = self
                .inner
                .chunks
                .read()
                .await
                .get(&id)
                .is_some_and(|s| s.drained);
            if already {
                return;
            }
            notify.notified().await;
        }
    }

    /// Look up the (chunk_id, pk_column, pk_range, low_set, high_set)
    /// for every active chunk belonging to the given `(schema, table)`.
    /// Used by the consumer to know which chunks an incoming event might
    /// affect, without holding the registry lock for the whole
    /// event-processing pass.
    pub async fn chunks_for_table(&self, schema: &str, table: &str) -> Vec<ChunkSnapshot> {
        self.inner
            .chunks
            .read()
            .await
            .iter()
            .filter(|(_, s)| s.table.0 == schema && s.table.1 == table)
            .map(|(id, s)| ChunkSnapshot {
                id: *id,
                pk_column: s.pk_column.clone(),
                pk_range: s.pk_range.clone(),
                low_set: s.low_set.clone(),
                high_set: s.high_set.clone(),
            })
            .collect()
    }

    /// Internal: drop a chunk from the registry. Called by `ChunkHandle::Drop`
    /// or directly by the worker when it finishes processing.
    pub async fn deregister(&self, id: ChunkId) {
        self.inner.chunks.write().await.remove(&id);
    }

    /// Number of currently-registered chunks. Test/diagnostics only.
    /// (`is_empty` would also need to acquire the read lock, so it is not
    /// provided as a "free" alternative; check `len() == 0` if needed.)
    #[allow(clippy::len_without_is_empty)]
    pub async fn len(&self) -> usize {
        self.inner.chunks.read().await.len()
    }
}

/// Read-only snapshot of a chunk used by the consumer to evaluate event
/// membership without holding the registry write lock.
#[derive(Debug, Clone)]
pub struct ChunkSnapshot {
    pub id: ChunkId,
    pub pk_column: String,
    pub pk_range: (Value, Value),
    pub low_set: GtidSet,
    pub high_set: Option<GtidSet>,
}

/// Returns true iff `pk` is inside the chunk's inclusive PK range using
/// the same comparison logic the snapshot worker uses to build chunks.
/// Single-column primary keys only.
pub fn pk_in_range(pk: &Value, range: &(Value, Value)) -> bool {
    cmp_value(pk, &range.0).is_ge() && cmp_value(pk, &range.1).is_le()
}

fn cmp_value(a: &Value, b: &Value) -> std::cmp::Ordering {
    use std::cmp::Ordering;
    match (a, b) {
        (Value::Int64(x), Value::Int64(y)) => x.cmp(y),
        (Value::String(x), Value::String(y)) => x.cmp(y),
        (Value::Uuid(x), Value::Uuid(y)) => x.cmp(y),
        (Value::Decimal(x), Value::Decimal(y)) => x.cmp(y),
        (Value::Timestamp(x), Value::Timestamp(y)) => x.cmp(y),
        // Falling back to equality: types we don't know how to order
        // are treated as not-in-range, which is conservative (the chunk
        // simply emits the snapshot row; no eviction). The snapshot
        // module only chunks on integer / string / uuid PKs today.
        _ => Ordering::Equal,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Duration;

    fn empty_set() -> GtidSet {
        GtidSet::parse("").unwrap()
    }

    #[tokio::test]
    async fn register_and_deregister() {
        let registry = ActiveChunks::new();
        assert_eq!(registry.len().await, 0);

        let (handle, _notify) = registry
            .register(
                ("db".into(), "t".into()),
                "id".into(),
                (Value::Int64(1), Value::Int64(100)),
                empty_set(),
            )
            .await;
        assert_eq!(registry.len().await, 1);

        let id = handle.id();
        registry.deregister(id).await;
        assert_eq!(registry.len().await, 0);
        std::mem::forget(handle); // we already deregistered manually
    }

    #[tokio::test]
    async fn record_eviction_idempotent() {
        let registry = ActiveChunks::new();
        let (handle, _notify) = registry
            .register(
                ("db".into(), "t".into()),
                "id".into(),
                (Value::Int64(1), Value::Int64(100)),
                empty_set(),
            )
            .await;

        registry
            .record_eviction(handle.id(), &Value::Int64(42))
            .await;
        registry
            .record_eviction(handle.id(), &Value::Int64(42))
            .await;
        let evicted = registry.evicted_pks(handle.id()).await;
        assert_eq!(evicted.len(), 1);
        assert!(evicted.contains(&pk_key(&Value::Int64(42))));
        std::mem::forget(handle);
    }

    #[tokio::test]
    async fn await_drain_blocks_until_high_watermark_covered() {
        let registry = ActiveChunks::new();
        let low = GtidSet::parse("uuid:1-10").unwrap();
        let (handle, notify) = registry
            .register(
                ("db".into(), "t".into()),
                "id".into(),
                (Value::Int64(1), Value::Int64(100)),
                low,
            )
            .await;
        let id = handle.id();

        // No high_set yet, no drain — await_drain must not return.
        let registry_clone = registry.clone();
        let notify_clone = notify.clone();
        let handle_id = id;
        let waiter =
            tokio::spawn(async move { registry_clone.await_drain(handle_id, notify_clone).await });

        tokio::time::sleep(Duration::from_millis(20)).await;
        assert!(!waiter.is_finished(), "must not return without drain");

        // Set a high watermark; consumer hasn't drained past it yet.
        let high = GtidSet::parse("uuid:1-50").unwrap();
        registry.set_high_watermark(id, high.clone()).await;

        // Consumer drains exactly to the high watermark.
        registry.try_drain(&high).await;

        tokio::time::timeout(Duration::from_secs(1), waiter)
            .await
            .expect("await_drain returned within timeout")
            .unwrap();
        std::mem::forget(handle);
    }

    #[tokio::test]
    async fn try_drain_does_not_signal_with_partial_coverage() {
        let registry = ActiveChunks::new();
        let (handle, _notify) = registry
            .register(
                ("db".into(), "t".into()),
                "id".into(),
                (Value::Int64(1), Value::Int64(100)),
                empty_set(),
            )
            .await;
        registry
            .set_high_watermark(handle.id(), GtidSet::parse("uuid:1-100").unwrap())
            .await;

        // Consumer at 1-50 — not enough.
        registry
            .try_drain(&GtidSet::parse("uuid:1-50").unwrap())
            .await;
        let snap = &registry.chunks_for_table("db", "t").await;
        assert!(!snap.is_empty());

        // Now drained.
        registry
            .try_drain(&GtidSet::parse("uuid:1-100").unwrap())
            .await;
        // (We don't expose `drained` on the snapshot; the await_drain
        // test above covers the wake-up path.)
        std::mem::forget(handle);
    }

    #[tokio::test]
    async fn chunks_for_table_filters() {
        let registry = ActiveChunks::new();
        let (h1, _) = registry
            .register(
                ("db".into(), "t1".into()),
                "id".into(),
                (Value::Int64(1), Value::Int64(50)),
                empty_set(),
            )
            .await;
        let (h2, _) = registry
            .register(
                ("db".into(), "t2".into()),
                "id".into(),
                (Value::Int64(1), Value::Int64(50)),
                empty_set(),
            )
            .await;
        let snap = registry.chunks_for_table("db", "t1").await;
        assert_eq!(snap.len(), 1);
        assert_eq!(snap[0].id, h1.id());
        std::mem::forget(h1);
        std::mem::forget(h2);
    }

    #[test]
    fn pk_in_range_inclusive() {
        let r = (Value::Int64(10), Value::Int64(20));
        assert!(pk_in_range(&Value::Int64(10), &r));
        assert!(pk_in_range(&Value::Int64(15), &r));
        assert!(pk_in_range(&Value::Int64(20), &r));
        assert!(!pk_in_range(&Value::Int64(9), &r));
        assert!(!pk_in_range(&Value::Int64(21), &r));
    }

    #[test]
    fn pk_in_range_string() {
        let r = (Value::String("a".into()), Value::String("m".into()));
        assert!(pk_in_range(&Value::String("a".into()), &r));
        assert!(pk_in_range(&Value::String("g".into()), &r));
        assert!(pk_in_range(&Value::String("m".into()), &r));
        assert!(!pk_in_range(&Value::String("z".into()), &r));
    }
}
