//! Programmatic docker-compose YAML generation for a (source, sink) pair.
//!
//! Infers which Docker containers to create based on well-known localhost
//! ports in spec URLs:
//!
//!   localhost:15432 source → source-pg container
//!   localhost:18030 sink   → sink-starrocks container
//!   localhost:25432 sink   → sink-pg container
//!   remote URLs            → only dbmazz container

use std::path::PathBuf;

use sha2::{Digest, Sha256};
use url::Url;

use crate::config::schema::*;
use crate::paths;

// ── Well-known localhost ports ─────────────────────────────────────────────

const SOURCE_PG_EXT_PORT: u16 = 15432;
const SOURCE_PG_INT_PORT: u16 = 5432;
const SOURCE_PG_SERVICE: &str = "source-pg";

const SINK_PG_EXT_PORT: u16 = 25432;
const SINK_PG_INT_PORT: u16 = 5432;
const SINK_PG_SERVICE: &str = "sink-pg";

const SINK_SR_HTTP_EXT_PORT: u16 = 18030;
const SINK_SR_HTTP_INT_PORT: u16 = 8030;
const SINK_SR_MYSQL_INT_PORT: u16 = 9030;
const SINK_SR_SERVICE: &str = "sink-starrocks";

const INFRA_PROJECT_NAME: &str = "ez-cdc-infra";

// ── URL helpers ────────────────────────────────────────────────────────────

fn extract_port(url_str: &str) -> Option<u16> {
    Url::parse(url_str).ok().and_then(|u| u.port())
}

fn rewrite_url_for_docker(url_str: &str, ext_port: u16, int_port: u16, service: &str) -> String {
    let Ok(parsed) = Url::parse(url_str) else {
        return url_str.to_string();
    };

    let is_local = matches!(parsed.host_str(), Some("localhost") | Some("127.0.0.1"));
    if !is_local || parsed.port() != Some(ext_port) {
        return url_str.to_string();
    }

    let mut rewritten = parsed.clone();
    let _ = rewritten.set_host(Some(service));
    let _ = rewritten.set_port(Some(int_port));
    rewritten.to_string()
}

// ── Cache layout ───────────────────────────────────────────────────────────

fn cache_root() -> PathBuf {
    paths::CLI_DIR.join(".cache").join("compose")
}

/// Return the cache directory for a (source_name, sink_name) pair.
pub fn cache_dir_for(source_name: &str, sink_name: &str) -> PathBuf {
    let key = format!("{source_name}|{sink_name}");
    let mut hasher = Sha256::new();
    hasher.update(key.as_bytes());
    let digest = format!("{:x}", hasher.finalize());
    let short = &digest[..8];
    cache_root().join(format!("{source_name}__{sink_name}__{short}"))
}

// ── Top-level builders ─────────────────────────────────────────────────────

/// Generate compose.yml + .env for a (source, sink) pair.
///
/// The compose contains **only the dbmazz service**, connected to the
/// infra network. Returns `(compose_path, env_path)`.
pub fn build_compose_for_pair(
    source_name: &str,
    source: &SourceSpec,
    sink_name: &str,
    sink: &SinkSpec,
    settings: &PipelineSettings,
) -> Result<(PathBuf, PathBuf), String> {
    let cache = cache_dir_for(source_name, sink_name);
    std::fs::create_dir_all(&cache).map_err(|e| format!("create cache dir: {e}"))?;

    let project_name = format!("ez-cdc-{}-{}", source_name, sink_name)
        .replace('_', "-")
        .chars()
        .take(50)
        .collect::<String>();

    let infra_network = format!("{INFRA_PROJECT_NAME}_dbmazz");

    // Build dbmazz service.
    let mut dbmazz_service = build_dbmazz_service(source, sink);
    // Override network to use infra compose's network.
    dbmazz_service.insert(
        "networks".into(),
        serde_json::json!([&infra_network]),
    );
    // Remove depends_on — infra services live in a different compose.
    dbmazz_service.remove("depends_on");

    let compose_dict = serde_json::json!({
        "name": project_name,
        "services": {
            "dbmazz": dbmazz_service,
        },
        "networks": {
            &infra_network: { "external": true },
        },
    });

    // Write .env file.
    let env_path = cache.join(".env");
    let env_content = build_env_file(source, sink, settings);
    std::fs::write(&env_path, &env_content)
        .map_err(|e| format!("write .env: {e}"))?;

    // Write compose.yml.
    let compose_path = cache.join("compose.yml");
    let compose_yaml = format!(
        "# ez-cdc generated docker compose — dbmazz only (infra is separate)\n\
         # source: {source_name}\n\
         # sink:   {sink_name}\n\
         # Generated by ez-cdc — do not edit by hand.\n\n{}",
        serde_yml::to_string(&compose_dict).map_err(|e| format!("serialize compose: {e}"))?
    );
    std::fs::write(&compose_path, &compose_yaml)
        .map_err(|e| format!("write compose.yml: {e}"))?;

    Ok((compose_path, env_path))
}

// ── Service builders ───────────────────────────────────────────────────────

fn build_dbmazz_service(source: &SourceSpec, sink: &SinkSpec) -> serde_json::Map<String, serde_json::Value> {
    let mut depends_on = serde_json::Map::new();

    match source {
        SourceSpec::Postgres(inner) => {
            if extract_port(&inner.url) == Some(SOURCE_PG_EXT_PORT) {
                depends_on.insert(
                    "source-pg".into(),
                    serde_json::json!({"condition": "service_healthy"}),
                );
            }
        }
    }

    match sink {
        SinkSpec::Starrocks(sr) => {
            if extract_port(&sr.url) == Some(SINK_SR_HTTP_EXT_PORT) {
                depends_on.insert(
                    "sink-starrocks-init".into(),
                    serde_json::json!({"condition": "service_completed_successfully"}),
                );
            }
        }
        SinkSpec::Postgres(pg) => {
            if extract_port(&pg.url) == Some(SINK_PG_EXT_PORT) {
                depends_on.insert(
                    "sink-pg".into(),
                    serde_json::json!({"condition": "service_healthy"}),
                );
            }
        }
        SinkSpec::Snowflake(_) => {}
    }

    // Use the official dbmazz image from GHCR. The version is pinned to
    // the CLI's own CARGO_PKG_VERSION, overridable via the DBMAZZ_IMAGE
    // env var for local-dev testing of patched daemons.
    let mut service = serde_json::Map::new();
    service.insert("image".into(), serde_json::json!(crate::commands::dbmazz_image()));
    service.insert("ports".into(), serde_json::json!(["8080:8080", "50051:50051"]));
    service.insert("env_file".into(), serde_json::json!([".env"]));
    service.insert("restart".into(), serde_json::json!("unless-stopped"));
    service.insert("healthcheck".into(), serde_json::json!({
        "test": ["CMD", "curl", "-sf", "http://localhost:8080/healthz"],
        "interval": "5s",
        "timeout": "3s",
        "retries": 12,
        "start_period": "10s",
    }));
    service.insert("networks".into(), serde_json::json!(["dbmazz"]));
    if !depends_on.is_empty() {
        service.insert("depends_on".into(), serde_json::Value::Object(depends_on));
    }

    service
}

// ── Env file generation ────────────────────────────────────────────────────

fn build_env_file(source: &SourceSpec, sink: &SinkSpec, settings: &PipelineSettings) -> String {
    let mut lines = vec![
        "# Generated by ez-cdc — do not edit by hand".into(),
        String::new(),
    ];

    // Source vars.
    match source {
        SourceSpec::Postgres(inner) => {
            let mut source_url = rewrite_url_for_docker(
                &inner.url,
                SOURCE_PG_EXT_PORT,
                SOURCE_PG_INT_PORT,
                SOURCE_PG_SERVICE,
            );
            if !source_url.contains("replication=database") {
                let sep = if source_url.contains('?') { "&" } else { "?" };
                source_url = format!("{source_url}{sep}replication=database");
            }

            lines.push("SOURCE_TYPE=postgres".into());
            lines.push(format!("SOURCE_URL={source_url}"));
            lines.push(format!("SOURCE_SLOT_NAME={}", inner.replication_slot));
            lines.push(format!("SOURCE_PUBLICATION_NAME={}", inner.publication));
            lines.push(format!("TABLES={}", inner.tables.join(",")));
            lines.push(String::new());
        }
    }

    // Sink vars.
    match sink {
        SinkSpec::Postgres(pg) => {
            let sink_url = rewrite_url_for_docker(
                &pg.url,
                SINK_PG_EXT_PORT,
                SINK_PG_INT_PORT,
                SINK_PG_SERVICE,
            );
            lines.push("SINK_TYPE=postgres".into());
            lines.push(format!("SINK_URL={sink_url}"));
            lines.push(format!("SINK_DATABASE={}", pg.database));
            lines.push(format!("SINK_SCHEMA={}", pg.schema_name));
        }
        SinkSpec::Starrocks(sr) => {
            let sink_url = rewrite_url_for_docker(
                &sr.url,
                SINK_SR_HTTP_EXT_PORT,
                SINK_SR_HTTP_INT_PORT,
                SINK_SR_SERVICE,
            );
            // If URL was rewritten, use internal MySQL port.
            let mysql_port = if sink_url != sr.url {
                SINK_SR_MYSQL_INT_PORT
            } else {
                sr.mysql_port
            };
            lines.push("SINK_TYPE=starrocks".into());
            lines.push(format!("SINK_URL={sink_url}"));
            lines.push(format!("SINK_PORT={mysql_port}"));
            lines.push(format!("SINK_DATABASE={}", sr.database));
            lines.push(format!("SINK_USER={}", sr.user));
            lines.push(format!("SINK_PASSWORD={}", sr.password));
        }
        SinkSpec::Snowflake(sf) => {
            lines.push("SINK_TYPE=snowflake".into());
            lines.push(format!("SINK_SNOWFLAKE_ACCOUNT={}", sf.account));
            lines.push(format!("SINK_USER={}", sf.user));
            lines.push(format!("SINK_PASSWORD={}", sf.password));
            lines.push(format!("SINK_DATABASE={}", sf.database));
            lines.push(format!("SINK_SCHEMA={}", sf.schema_name));
            lines.push(format!("SINK_SNOWFLAKE_WAREHOUSE={}", sf.warehouse));
            lines.push(format!(
                "SINK_SNOWFLAKE_SOFT_DELETE={}",
                if sf.soft_delete { "true" } else { "false" }
            ));
            if let Some(role) = &sf.role {
                lines.push(format!("SINK_SNOWFLAKE_ROLE={role}"));
            }
            if let Some(key_path) = &sf.private_key_path {
                lines.push(format!("SINK_SNOWFLAKE_PRIVATE_KEY_PATH={key_path}"));
            }
        }
    }

    lines.push(String::new());
    lines.push("# Pipeline / snapshot / logging (from ez-cdc.yaml settings:)".into());
    lines.extend(settings.to_env_lines());
    lines.push(String::new());
    lines.push("# Ports (fixed by compose service ports mapping)".into());
    lines.push("HTTP_API_PORT=8080".into());
    lines.push("GRPC_PORT=50051".into());
    lines.push(String::new());

    lines.join("\n")
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cache_dir_deterministic() {
        let a = cache_dir_for("demo-pg", "demo-sr");
        let b = cache_dir_for("demo-pg", "demo-sr");
        assert_eq!(a, b);
    }

    #[test]
    fn cache_dir_different_pairs() {
        let a = cache_dir_for("demo-pg", "demo-sr");
        let b = cache_dir_for("demo-pg", "demo-pg-target");
        assert_ne!(a, b);
    }

    #[test]
    fn extract_port_works() {
        assert_eq!(extract_port("postgres://user:pass@localhost:15432/db"), Some(15432));
        assert_eq!(extract_port("http://localhost:18030"), Some(18030));
        assert_eq!(extract_port("http://remote-host/path"), None);
        assert_eq!(extract_port("not-a-url"), None);
    }

    #[test]
    fn rewrite_localhost_url() {
        let result = rewrite_url_for_docker(
            "postgres://postgres:postgres@localhost:15432/dbmazz",
            15432,
            5432,
            "source-pg",
        );
        assert!(result.contains("source-pg"));
        assert!(result.contains(":5432"));
        assert!(!result.contains("localhost"));
    }

    #[test]
    fn no_rewrite_remote_url() {
        let url = "postgres://user:pass@remote.host:5432/db";
        let result = rewrite_url_for_docker(url, 15432, 5432, "source-pg");
        assert_eq!(result, url);
    }

    #[test]
    fn env_file_postgres_sink() {
        let source = SourceSpec::Postgres(PostgresSourceInner {
            url: "postgres://postgres:postgres@localhost:15432/dbmazz".into(),
            seed: None,
            replication_slot: "dbmazz_slot".into(),
            publication: "dbmazz_pub".into(),
            tables: vec!["orders".into(), "order_items".into()],
        });
        let sink = SinkSpec::Postgres(PostgresSinkInner {
            url: "postgres://postgres:postgres@localhost:25432/dbmazz_target".into(),
            database: "dbmazz_target".into(),
            schema_name: "public".into(),
        });
        let settings = PipelineSettings::default();
        let env = build_env_file(&source, &sink, &settings);

        assert!(env.contains("SOURCE_TYPE=postgres"));
        assert!(env.contains("source-pg:5432"));
        assert!(env.contains("replication=database"));
        assert!(env.contains("SINK_TYPE=postgres"));
        assert!(env.contains("sink-pg:5432"));
        assert!(env.contains("TABLES=orders,order_items"));
        assert!(env.contains("FLUSH_SIZE=10000"));
    }

    #[test]
    fn env_file_starrocks_sink() {
        let source = SourceSpec::Postgres(PostgresSourceInner {
            url: "postgres://localhost:15432/db".into(),
            seed: None,
            replication_slot: "slot".into(),
            publication: "pub".into(),
            tables: vec!["t1".into()],
        });
        let sink = SinkSpec::Starrocks(StarRocksSinkInner {
            url: "http://localhost:18030".into(),
            mysql_port: 19030,
            database: "dbmazz".into(),
            user: "root".into(),
            password: "".into(),
        });
        let settings = PipelineSettings::default();
        let env = build_env_file(&source, &sink, &settings);

        assert!(env.contains("SINK_TYPE=starrocks"));
        assert!(env.contains("sink-starrocks:8030"));
        assert!(env.contains(&format!("SINK_PORT={SINK_SR_MYSQL_INT_PORT}")));
    }
}
