//! Programmatic docker-compose YAML generation for a single (source, sink) pair.
//!
//! The CLI only manages the `dbmazz` daemon container. Source and sink
//! infrastructure is brought by the user (native on the host, their own
//! docker-compose, or a remote cloud endpoint).
//!
//! Networking model:
//!
//! - The dbmazz container is started via docker-compose using the default
//!   bridge network, plus `extra_hosts: ["host.docker.internal:host-gateway"]`
//!   so the same hostname resolves to the host on macOS, Linux, and Windows.
//! - URLs the user writes as `localhost:<port>` in `ez-cdc.yaml` are
//!   translated to `host.docker.internal:<port>` when the `.env` file is
//!   generated, so the container reaches the host loopback transparently.
//! - Remote URLs (anything that is not `localhost` / `127.0.0.1` /
//!   `0.0.0.0`) pass through unchanged.

use std::path::PathBuf;

use sha2::{Digest, Sha256};
use url::Url;

use crate::config::schema::*;
use crate::paths;

// ── URL helpers ────────────────────────────────────────────────────────────

/// Rewrite a local-loopback URL so that a process running inside a
/// Docker container can reach the same service on the host.
///
/// `localhost`, `127.0.0.1`, and `0.0.0.0` all become
/// `host.docker.internal`. Any other host is returned unchanged. Port,
/// path, query, and credentials are preserved. The trailing-slash
/// shape of the original URL is preserved (url::Url::to_string always
/// appends `/` when the path is empty, which breaks StarRocks Stream
/// Load POSTs that expect `<url>/api/...`).
fn rewrite_url_for_docker(url_str: &str) -> String {
    let Ok(parsed) = Url::parse(url_str) else {
        return url_str.to_string();
    };
    let is_local = matches!(
        parsed.host_str(),
        Some("localhost") | Some("127.0.0.1") | Some("0.0.0.0")
    );
    if !is_local {
        return url_str.to_string();
    }
    let mut rewritten = parsed;
    let _ = rewritten.set_host(Some("host.docker.internal"));
    let out = rewritten.to_string();
    if !url_str.ends_with('/') && out.ends_with('/') {
        return out.trim_end_matches('/').to_string();
    }
    out
}

#[allow(dead_code)]
fn extract_port(url_str: &str) -> Option<u16> {
    Url::parse(url_str).ok().and_then(|u| u.port())
}

// ── Cache layout ───────────────────────────────────────────────────────────

fn cache_root() -> PathBuf {
    paths::CLI_DIR.join(".cache").join("compose")
}

/// Return the cache directory for a (source_name, sink_name) pair.
pub fn cache_dir_for(source_name: &str, sink_name: &str) -> PathBuf {
    let key = format!("{source_name}|{sink_name}");
    let mut hasher = Sha256::new();
    hasher.update(key.as_bytes());
    let digest = format!("{:x}", hasher.finalize());
    let short = &digest[..8];
    cache_root().join(format!("{source_name}__{sink_name}__{short}"))
}

// ── Top-level builders ─────────────────────────────────────────────────────

/// Generate compose.yml + .env for a single (source, sink) pair.
///
/// The compose contains only the `dbmazz` daemon service. It uses the
/// default docker-compose bridge network with `extra_hosts` set so that
/// the container can reach services running on the host (native or
/// in sibling containers that publish ports) via
/// `host.docker.internal`. Returns `(compose_path, env_path)`.
pub fn build_compose_for_pair(
    source_name: &str,
    source: &SourceSpec,
    sink_name: &str,
    sink: &SinkSpec,
    settings: &PipelineSettings,
) -> Result<(PathBuf, PathBuf), String> {
    let cache = cache_dir_for(source_name, sink_name);
    std::fs::create_dir_all(&cache).map_err(|e| format!("create cache dir: {e}"))?;

    let project_name = format!("ez-cdc-{}-{}", source_name, sink_name)
        .replace('_', "-")
        .chars()
        .take(50)
        .collect::<String>();

    let dbmazz_service = build_dbmazz_service();

    let compose_dict = serde_json::json!({
        "name": project_name,
        "services": {
            "dbmazz": dbmazz_service,
        },
    });

    // Write .env file.
    let env_path = cache.join(".env");
    let env_content = build_env_file(source, sink, settings);
    std::fs::write(&env_path, &env_content)
        .map_err(|e| format!("write .env: {e}"))?;

    // Write compose.yml.
    let compose_path = cache.join("compose.yml");
    let compose_yaml = format!(
        "# ez-cdc generated docker compose — dbmazz daemon only\n\
         # source: {source_name}\n\
         # sink:   {sink_name}\n\
         # Generated by ez-cdc — do not edit by hand.\n\n{}",
        serde_yml::to_string(&compose_dict).map_err(|e| format!("serialize compose: {e}"))?
    );
    std::fs::write(&compose_path, &compose_yaml)
        .map_err(|e| format!("write compose.yml: {e}"))?;

    Ok((compose_path, env_path))
}

// ── Service builders ───────────────────────────────────────────────────────

/// Build the compose service definition for the dbmazz daemon.
///
/// Uses the official image from GHCR, pinned to the CLI's own
/// `CARGO_PKG_VERSION` (overridable with the `DBMAZZ_IMAGE` env var for
/// local-dev testing of patched daemons). Adds `extra_hosts` so the
/// container can reach services on the host via `host.docker.internal`
/// on every supported platform.
fn build_dbmazz_service() -> serde_json::Map<String, serde_json::Value> {
    let mut service = serde_json::Map::new();
    service.insert("image".into(), serde_json::json!(crate::commands::dbmazz_image()));
    service.insert("ports".into(), serde_json::json!(["8080:8080", "50051:50051"]));
    service.insert("env_file".into(), serde_json::json!([".env"]));
    service.insert("restart".into(), serde_json::json!("unless-stopped"));
    // `host-gateway` is a Docker reserved string that resolves to the
    // host IP from inside the container. It works natively on Docker
    // Desktop (macOS/Windows) and on Docker Engine 20.10+ on Linux.
    service.insert(
        "extra_hosts".into(),
        serde_json::json!(["host.docker.internal:host-gateway"]),
    );
    service.insert("healthcheck".into(), serde_json::json!({
        "test": ["CMD", "curl", "-sf", "http://localhost:8080/healthz"],
        "interval": "5s",
        "timeout": "3s",
        "retries": 12,
        "start_period": "10s",
    }));
    service
}

// ── Env file generation ────────────────────────────────────────────────────

fn build_env_file(source: &SourceSpec, sink: &SinkSpec, settings: &PipelineSettings) -> String {
    let mut lines = vec![
        "# Generated by ez-cdc — do not edit by hand".into(),
        String::new(),
    ];

    // Source vars.
    match source {
        SourceSpec::Postgres(inner) => {
            let mut source_url = rewrite_url_for_docker(&inner.url);
            if !source_url.contains("replication=database") {
                let sep = if source_url.contains('?') { "&" } else { "?" };
                source_url = format!("{source_url}{sep}replication=database");
            }

            lines.push("SOURCE_TYPE=postgres".into());
            lines.push(format!("SOURCE_URL={source_url}"));
            lines.push(format!("SOURCE_SLOT_NAME={}", inner.replication_slot));
            lines.push(format!("SOURCE_PUBLICATION_NAME={}", inner.publication));
            lines.push(format!("TABLES={}", inner.tables.join(",")));
            lines.push(String::new());
        }
    }

    // Sink vars.
    match sink {
        SinkSpec::Postgres(pg) => {
            let sink_url = rewrite_url_for_docker(&pg.url);
            lines.push("SINK_TYPE=postgres".into());
            lines.push(format!("SINK_URL={sink_url}"));
            lines.push(format!("SINK_DATABASE={}", pg.database));
            lines.push(format!("SINK_SCHEMA={}", pg.schema_name));
        }
        SinkSpec::Starrocks(sr) => {
            let sink_url = rewrite_url_for_docker(&sr.url);
            lines.push("SINK_TYPE=starrocks".into());
            lines.push(format!("SINK_URL={sink_url}"));
            lines.push(format!("SINK_PORT={}", sr.mysql_port));
            lines.push(format!("SINK_DATABASE={}", sr.database));
            lines.push(format!("SINK_USER={}", sr.user));
            lines.push(format!("SINK_PASSWORD={}", sr.password));
        }
        SinkSpec::Snowflake(sf) => {
            lines.push("SINK_TYPE=snowflake".into());
            lines.push(format!("SINK_SNOWFLAKE_ACCOUNT={}", sf.account));
            lines.push(format!("SINK_USER={}", sf.user));
            lines.push(format!("SINK_PASSWORD={}", sf.password));
            lines.push(format!("SINK_DATABASE={}", sf.database));
            lines.push(format!("SINK_SCHEMA={}", sf.schema_name));
            lines.push(format!("SINK_SNOWFLAKE_WAREHOUSE={}", sf.warehouse));
            lines.push(format!(
                "SINK_SNOWFLAKE_SOFT_DELETE={}",
                if sf.soft_delete { "true" } else { "false" }
            ));
            if let Some(role) = &sf.role {
                lines.push(format!("SINK_SNOWFLAKE_ROLE={role}"));
            }
            if let Some(key_path) = &sf.private_key_path {
                lines.push(format!("SINK_SNOWFLAKE_PRIVATE_KEY_PATH={key_path}"));
            }
        }
    }

    lines.push(String::new());
    lines.push("# Pipeline / snapshot / logging (from ez-cdc.yaml settings:)".into());
    lines.extend(settings.to_env_lines());
    lines.push(String::new());
    lines.push("# Ports (fixed by compose service ports mapping)".into());
    lines.push("HTTP_API_PORT=8080".into());
    lines.push("GRPC_PORT=50051".into());
    lines.push(String::new());

    lines.join("\n")
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cache_dir_deterministic() {
        let a = cache_dir_for("demo-pg", "demo-sr");
        let b = cache_dir_for("demo-pg", "demo-sr");
        assert_eq!(a, b);
    }

    #[test]
    fn cache_dir_different_pairs() {
        let a = cache_dir_for("demo-pg", "demo-sr");
        let b = cache_dir_for("demo-pg", "demo-pg-target");
        assert_ne!(a, b);
    }

    #[test]
    fn extract_port_works() {
        assert_eq!(extract_port("postgres://user:pass@localhost:15432/db"), Some(15432));
        assert_eq!(extract_port("http://localhost:18030"), Some(18030));
        assert_eq!(extract_port("http://remote-host/path"), None);
        assert_eq!(extract_port("not-a-url"), None);
    }

    #[test]
    fn rewrite_localhost_url_preserves_port_and_path() {
        let result = rewrite_url_for_docker(
            "postgres://postgres:postgres@localhost:5432/dbmazz?replication=database",
        );
        assert_eq!(
            result,
            "postgres://postgres:postgres@host.docker.internal:5432/dbmazz?replication=database"
        );
    }

    #[test]
    fn rewrite_127_0_0_1_and_0_0_0_0() {
        assert_eq!(
            rewrite_url_for_docker("http://127.0.0.1:8030"),
            "http://host.docker.internal:8030"
        );
        assert_eq!(
            rewrite_url_for_docker("http://0.0.0.0:9999/api"),
            "http://host.docker.internal:9999/api"
        );
    }

    #[test]
    fn no_rewrite_remote_url() {
        let url = "postgres://user:pass@remote.host:5432/db";
        assert_eq!(rewrite_url_for_docker(url), url);
    }

    #[test]
    fn no_rewrite_cloud_hostname() {
        let url = "https://xy12345.us-east-1.snowflakecomputing.com";
        assert_eq!(rewrite_url_for_docker(url), url);
    }

    #[test]
    fn env_file_postgres_sink() {
        let source = SourceSpec::Postgres(PostgresSourceInner {
            url: "postgres://postgres:postgres@localhost:5432/dbmazz".into(),
            seed: None,
            replication_slot: "dbmazz_slot".into(),
            publication: "dbmazz_pub".into(),
            tables: vec!["orders".into(), "order_items".into()],
        });
        let sink = SinkSpec::Postgres(PostgresSinkInner {
            url: "postgres://postgres:postgres@localhost:5433/dbmazz_target".into(),
            database: "dbmazz_target".into(),
            schema_name: "public".into(),
        });
        let settings = PipelineSettings::default();
        let env = build_env_file(&source, &sink, &settings);

        assert!(env.contains("SOURCE_TYPE=postgres"));
        assert!(env.contains("host.docker.internal:5432"));
        assert!(env.contains("replication=database"));
        assert!(env.contains("SINK_TYPE=postgres"));
        assert!(env.contains("host.docker.internal:5433"));
        assert!(env.contains("TABLES=orders,order_items"));
        assert!(env.contains("FLUSH_SIZE=10000"));
    }

    #[test]
    fn env_file_starrocks_sink() {
        let source = SourceSpec::Postgres(PostgresSourceInner {
            url: "postgres://localhost:5432/db".into(),
            seed: None,
            replication_slot: "slot".into(),
            publication: "pub".into(),
            tables: vec!["t1".into()],
        });
        let sink = SinkSpec::Starrocks(StarRocksSinkInner {
            url: "http://localhost:8030".into(),
            mysql_port: 9030,
            database: "dbmazz".into(),
            user: "root".into(),
            password: "".into(),
        });
        let settings = PipelineSettings::default();
        let env = build_env_file(&source, &sink, &settings);

        assert!(env.contains("SINK_TYPE=starrocks"));
        assert!(env.contains("SINK_URL=http://host.docker.internal:8030"));
        assert!(env.contains("SINK_PORT=9030"));
    }
}
