"""Docker compose wrapper.

Shells out to `docker compose` to manage stacks generated by compose_builder.
All operations work on a per-pair compose file (one .yml per source/sink
pair, written to e2e/.cache/compose/<pair>/) — there is no global compose
file in PR 4 onwards.

The legacy `profile` parameter from PR 1 is gone (along with the static
e2e/compose.yml). Each call passes the path to a generated compose file,
and docker compose treats it as its own project (the project name is
encoded in the compose file itself by compose_builder).
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Optional


class ComposeError(Exception):
    """Raised when a compose operation fails."""


def check_docker_compose() -> None:
    """Verify that `docker compose` is available. Raises if not."""
    if shutil.which("docker") is None:
        raise ComposeError(
            "docker is not installed or not in PATH. "
            "Install it from https://docs.docker.com/get-docker/"
        )

    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (subprocess.TimeoutExpired, OSError) as e:
        raise ComposeError(f"Failed to run 'docker compose version': {e}") from e

    if result.returncode != 0:
        raise ComposeError(
            "'docker compose' is not available. The old 'docker-compose' binary is "
            "not supported — install Docker Desktop or the compose plugin: "
            "https://docs.docker.com/compose/install/"
        )


def _base_cmd(compose_file: Path) -> list[str]:
    """Build the base `docker compose -f <generated.yml>` command."""
    return ["docker", "compose", "-f", str(compose_file)]


def up(
    compose_file: Path,
    *,
    wait: bool = True,
    build: bool = False,
    services: list[str] | None = None,
) -> None:
    """Start the stack defined by a compose file.

    If `wait=True`, blocks until all services report healthy (via docker
    compose's --wait flag, which respects healthchecks defined in the file).

    If `build=True`, passes `--build` to force a rebuild of the dbmazz
    image. Default is False so repeat runs are fast — docker compose will
    reuse the cached image if present. Combined with the tight .dockerignore
    at the repo root, Python-only edits to the test harness never trigger
    a Rust recompile.

    If `services` is provided, only those services are started (instead of
    the whole stack).
    """
    check_docker_compose()

    cmd = _base_cmd(compose_file) + ["up", "-d"]
    if build:
        cmd.append("--build")
    if wait:
        cmd.append("--wait")
    if services:
        cmd.extend(services)

    result = subprocess.run(cmd, text=True)
    if result.returncode != 0:
        raise ComposeError(
            f"docker compose up failed for {compose_file.name} (exit {result.returncode})"
        )


def down(compose_file: Path, *, remove_volumes: bool = True, services: list[str] | None = None) -> None:
    """Stop and remove the stack defined by a compose file.

    With remove_volumes=True (the default) and no specific services, also
    removes named volumes so each test run starts from a clean state.

    If `services` is provided, only those services are stopped and removed
    via `stop_services()` — ``docker compose down`` does not accept service
    names.
    """
    check_docker_compose()

    if services:
        stop_services(compose_file, services)
        return

    cmd = _base_cmd(compose_file) + ["down"]
    if remove_volumes:
        cmd.append("-v")

    result = subprocess.run(cmd, text=True)
    if result.returncode != 0:
        raise ComposeError(
            f"docker compose down failed for {compose_file.name} (exit {result.returncode})"
        )


def logs(
    compose_file: Path,
    *,
    service: Optional[str] = None,
    follow: bool = False,
    tail: int = 100,
) -> None:
    """Stream logs for a stack (or a specific service within it)."""
    check_docker_compose()

    cmd = _base_cmd(compose_file) + ["logs", f"--tail={tail}"]
    if follow:
        cmd.append("-f")
    if service is not None:
        cmd.append(service)

    # Inherit stdio — user sees logs in real time, Ctrl+C stops.
    try:
        subprocess.run(cmd)
    except KeyboardInterrupt:
        pass


def ps(compose_file: Path) -> str:
    """Return the output of `docker compose ps` for a stack."""
    check_docker_compose()

    cmd = _base_cmd(compose_file) + ["ps"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout


def is_running(compose_file: Path) -> bool:
    """Check whether any container for this stack is currently running.

    Returns False if the compose file doesn't exist (e.g., the pair was
    never `up`'d) — that's a "not running" rather than an error.
    """
    if not compose_file.exists():
        return False
    check_docker_compose()

    cmd = _base_cmd(compose_file) + ["ps", "-q"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0 and result.stdout.strip() != ""


def stop_services(compose_file: Path, services: list[str]) -> None:
    """Stop and remove specific services (not the whole stack).

    ``docker compose down`` does not accept service names, so this uses
    ``docker compose stop`` followed by ``docker compose rm -f`` to
    achieve targeted teardown.
    """
    check_docker_compose()

    # Stop the services.
    cmd = _base_cmd(compose_file) + ["stop"] + services
    result = subprocess.run(cmd, text=True)
    if result.returncode != 0:
        raise ComposeError(
            f"docker compose stop failed for services {services} (exit {result.returncode})"
        )

    # Remove the stopped containers.
    cmd = _base_cmd(compose_file) + ["rm", "-f"] + services
    result = subprocess.run(cmd, text=True)
    if result.returncode != 0:
        raise ComposeError(
            f"docker compose rm failed for services {services} (exit {result.returncode})"
        )


def is_service_running(compose_file: Path, service: str) -> bool:
    """Check if a specific service has a running container.

    Returns False if the compose file doesn't exist (e.g., the pair was
    never `up`'d).
    """
    if not compose_file.exists():
        return False
    check_docker_compose()

    cmd = _base_cmd(compose_file) + ["ps", "-q", service]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0 and result.stdout.strip() != ""
